In [1]:
from datasets import load_dataset

ds = load_dataset("code-search-net/code_search_net", "python")
train_set = ds["train"]
val_set = ds["validation"]
test_set = ds["test"]

/Users/kuzeyaldemir/Projects/tiny-coder/.venv/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [2]:
import polars as pl

polars_train_df = train_set.to_polars()
display(polars_train_df)

shape: (412_178, 11)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ repositor ┆ func_path ┆ func_name ┆ whole_fun ┆ … ┆ func_docu ┆ func_docu ┆ split_nam ┆ func_cod │
│ y_name    ┆ _in_repos ┆ ---       ┆ c_string  ┆   ┆ mentation ┆ mentation ┆ e         ┆ e_url    │
│ ---       ┆ itory     ┆ str       ┆ ---       ┆   ┆ _string   ┆ _tokens   ┆ ---       ┆ ---      │
│ str       ┆ ---       ┆           ┆ str       ┆   ┆ ---       ┆ ---       ┆ str       ┆ str      │
│           ┆ str       ┆           ┆           ┆   ┆ str       ┆ list[str] ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ mjirik/im ┆ imcut/pyc ┆ ImageGrap ┆ def __msg ┆ … ┆ Estimate  ┆ ["Estimat ┆ train     ┆ https:// │
│ cut       ┆ ut.py     ┆ hCut.__ms ┆ c_step3_d ┆   ┆ discontin ┆ e", "disc ┆           ┆ github.c │
│           ┆           ┆ gc_step3_ ┆ iscontinu ┆   ┆ uity in   ┆ ontinuity ┆           ┆ om/mjiri │
│           ┆           ┆ dis…      ┆ ity…      ┆   ┆ basi…     ┆ ", …      ┆           ┆ k/imcu…  │
│ mjirik/im ┆ imcut/pyc ┆ ImageGrap ┆ def __mul ┆ … ┆ Run       ┆ ["Run",   ┆ train     ┆ https:// │
│ cut       ┆ ut.py     ┆ hCut.__mu ┆ tiscale_g ┆   ┆ Graph-Cut ┆ "Graph",  ┆           ┆ github.c │
│           ┆           ┆ ltiscale_ ┆ c_lo2hi_r ┆   ┆ segmentat ┆ … "use_bo ┆           ┆ om/mjiri │
│           ┆           ┆ gc_…      ┆ un(…      ┆   ┆ ion wit…  ┆ unda…     ┆           ┆ k/imcu…  │
│ mjirik/im ┆ imcut/pyc ┆ ImageGrap ┆ def __mul ┆ … ┆ Run       ┆ ["Run",   ┆ train     ┆ https:// │
│ cut       ┆ ut.py     ┆ hCut.__mu ┆ tiscale_g ┆   ┆ Graph-Cut ┆ "Graph",  ┆           ┆ github.c │
│           ┆           ┆ ltiscale_ ┆ c_hi2lo_r ┆   ┆ segmentat ┆ … "use_bo ┆           ┆ om/mjiri │
│           ┆           ┆ gc_…      ┆ un(…      ┆   ┆ ion wit…  ┆ unda…     ┆           ┆ k/imcu…  │
│ mjirik/im ┆ imcut/pyc ┆ ImageGrap ┆ def __ord ┆ … ┆ Return    ┆ ["Return" ┆ train     ┆ https:// │
│ cut       ┆ ut.py     ┆ hCut.__or ┆ ered_valu ┆   ┆ values    ┆ ,         ┆           ┆ github.c │
│           ┆           ┆ dered_val ┆ es_by_ind ┆   ┆ (intensit ┆ "values", ┆           ┆ om/mjiri │
│           ┆           ┆ ues…      ┆ exe…      ┆   ┆ ies) by…  ┆ … "."]    ┆           ┆ k/imcu…  │
│ mjirik/im ┆ imcut/pyc ┆ ImageGrap ┆ def __hi2 ┆ … ┆ Function  ┆ ["Functio ┆ train     ┆ https:// │
│ cut       ┆ ut.py     ┆ hCut.__hi ┆ lo_multis ┆   ┆ computes  ┆ n", "comp ┆           ┆ github.c │
│           ┆           ┆ 2lo_multi ┆ cale_inde ┆   ┆ multiscal ┆ utes", …  ┆           ┆ om/mjiri │
│           ┆           ┆ sca…      ┆ xes…      ┆   ┆ e i…      ┆ "."…      ┆           ┆ k/imcu…  │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ noxdafox/ ┆ clips/cla ┆ Class.ins ┆ def insta ┆ … ┆ Iterate   ┆ ["Iterate ┆ train     ┆ https:// │
│ clipspy   ┆ sses.py   ┆ tances    ┆ nces(self ┆   ┆ over the  ┆ ",        ┆           ┆ github.c │
│           ┆           ┆           ┆ ):        ┆   ┆ instances ┆ "over", … ┆           ┆ om/noxda │
│           ┆           ┆           ┆ "…        ┆   ┆ of …      ┆ "."]      ┆           ┆ fox/cl…  │
│ noxdafox/ ┆ clips/cla ┆ Class.sub ┆ def subcl ┆ … ┆ Iterate   ┆ ["Iterate ┆ train     ┆ https:// │
│ clipspy   ┆ sses.py   ┆ classes   ┆ asses(sel ┆   ┆ over the  ┆ ",        ┆           ┆ github.c │
│           ┆           ┆           ┆ f, inheri ┆   ┆ subclasse ┆ "over", … ┆           ┆ om/noxda │
│           ┆           ┆           ┆ ted…      ┆   ┆ s of…     ┆ "."]      ┆           ┆ fox/cl…  │
│ noxdafox/ ┆ clips/cla ┆ Class.sup ┆ def super ┆ … ┆ Iterate   ┆ ["Iterate ┆ train     ┆ https:// │
│ clipspy   ┆ sses.py   ┆ erclasses ┆ classes(s ┆   ┆ over the  ┆ ",        ┆           ┆ github.c │
│           ┆           ┆           ┆ elf,      ┆   ┆ superclas ┆ "over", … ┆           ┆ om/noxda │
│           ┆           ┆           ┆ inherit…  ┆   ┆ ses …     ┆ "."]      ┆           ┆ fox/cl…  │
│ noxdafox/ ┆ clips/cla ┆ Class.mes ┆ def messa ┆ … ┆ Iterate   ┆ ["Iterate ┆ train     ┆ https:// │
│ clipspy   ┆ sses.py   ┆ sage_hand ┆ ge_handle ┆   ┆ over the  ┆ ",        ┆           ┆ github.c │
│           ┆           ┆ lers      ┆ rs(self): ┆   ┆ message   ┆ "over", … ┆           ┆ om/noxda │
│           ┆           ┆           ┆   …       ┆   ┆ handl…    ┆ "."]      ┆           ┆ fox/cl…  │
│ noxdafox/ ┆ clips/cla ┆ Class.und ┆ def undef ┆ … ┆ Undefine  ┆ ["Undefin ┆ train     ┆ https:// │
│ clipspy   ┆ sses.py   ┆ efine     ┆ ine(self) ┆   ┆ the       ┆ e",       ┆           ┆ github.c │
│           ┆           ┆           ┆ :         ┆   ┆ Class.    ┆ "the", …  ┆           ┆ om/noxda │
│           ┆           ┆           ┆ ""…       ┆   ┆           ┆ "."]      ┆           ┆ fox/cl…  │
│           ┆           ┆           ┆           ┆   ┆ P…        ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [3]:
mean_length = polars_train_df.select(
    pl.col("whole_func_string").str.len_chars().mean().alias("mean_length")
)
mean_length

shape: (1, 1)
┌─────────────┐
│ mean_length │
│ ---         │
│ f64         │
╞═════════════╡
│ 1056.428514 │
└─────────────┘

In [4]:
for i in range(1):
    print(f"===== Example {i} =====")
    print(train_set[i]["whole_func_string"])
    print()

===== Example 0 =====
def __msgc_step3_discontinuity_localization(self):
        """
        Estimate discontinuity in basis of low resolution image segmentation.
        :return: discontinuity in low resolution
        """
        import scipy

        start = self._start_time
        seg = 1 - self.segmentation.astype(np.int8)
        self.stats["low level object voxels"] = np.sum(seg)
        self.stats["low level image voxels"] = np.prod(seg.shape)
        # in seg is now stored low resolution segmentation
        # back to normal parameters
        # step 2: discontinuity localization
        # self.segparams = sparams_hi
        seg_border = scipy.ndimage.filters.laplace(seg, mode="constant")
        logger.debug("seg_border: %s", scipy.stats.describe(seg_border, axis=None))
        # logger.debug(str(np.max(seg_border)))
        # logger.debug(str(np.min(seg_border)))
        seg_border[seg_border != 0] = 1
        logger.debug("seg_border: %s", scipy.stats.describe(seg_border, axis=None))
        # scipy.ndimage.morphology.distance_transform_edt
        boundary_dilatation_distance = self.segparams["boundary_dilatation_distance"]
        seg = scipy.ndimage.morphology.binary_dilation(
            seg_border,
            # seg,
            np.ones(
                [
                    (boundary_dilatation_distance * 2) + 1,
                    (boundary_dilatation_distance * 2) + 1,
                    (boundary_dilatation_distance * 2) + 1,
                ]
            ),
        )
        if self.keep_temp_properties:
            self.temp_msgc_lowres_discontinuity = seg
        else:
            self.temp_msgc_lowres_discontinuity = None

        if self.debug_images:
            import sed3

            pd = sed3.sed3(seg_border)  # ), contour=seg)
            pd.show()
            pd = sed3.sed3(seg)  # ), contour=seg)
            pd.show()
        # segzoom = scipy.ndimage.interpolation.zoom(seg.astype('float'), zoom,
        #                                                order=0).astype('int8')
        self.stats["t3"] = time.time() - start
        return seg

In [5]:
ex_bpe_ids = list(train_set[0]["whole_func_string"].encode("utf-8"))

sample_range = 10

print(ex_bpe_ids[:sample_range])
print(bytes(ex_bpe_ids)[:sample_range].decode("utf-8"))
print("Byte count:", len(ex_bpe_ids))

[100, 101, 102, 32, 95, 95, 109, 115, 103, 99]
def __msgc
Byte count: 2091

### Function for counting frequency of every adjacent pair

In [6]:
from collections import defaultdict
from collections.abc import Mapping

sample_string = "aaabbaababbaaabba"
sample_encoded = sample_string.encode("utf-8")

def pair_freq_counter(ids: list[int]) -> dict[tuple[int, int], int]:
    freq_counter = defaultdict(int)
    for idx in range(len(ids) - 1):
        curr = ids[idx]
        next = ids[idx + 1]
        freq_counter[curr, next] += 1
    return freq_counter

sample_freq_counter = pair_freq_counter(sample_encoded)

In [7]:
from collections.abc import Mapping

Pair = tuple[int, int]

def select_pair(
        freq_counter: Mapping[Pair, int],
        min_frequency: int = 2
) -> Pair | None:
    most_freq_pair = max(freq_counter.keys(), key=lambda x:freq_counter[x])
    if freq_counter[most_freq_pair] < min_frequency:
        return None
    return most_freq_pair

most_freq_pair = select_pair(sample_freq_counter)
print(list(sample_encoded))
print("Most frequent pair is:", most_freq_pair)

[97, 97, 97, 98, 98, 97, 97, 98, 97, 98, 98, 97, 97, 97, 98, 98, 97]
Most frequent pair is: (97, 97)

In [8]:
def apply_merge(
        ids: list[int],
        pair_to_merge: tuple[int, int],
        new_id: int
) -> list[int]:
    
    new_ids = []
    idx = 0
    # Manually loop over all adjacent pairs and apply merge if applicable
    while idx + 1 < len(ids):
        curr = ids[idx]
        next_token = ids[idx + 1]
        if curr == pair_to_merge[0] and next_token == pair_to_merge[1]:
            new_ids.append(new_id)
            idx += 2
        else:
            new_ids.append(curr)
            idx += 1
    # Add the last token to the new sequence
    if idx < len(ids):
        new_ids.append(ids[idx])
    
    return new_ids

merged_sample = apply_merge(sample_encoded, most_freq_pair, 256)
print(sample_string)
print("Before merging:")
print(list(sample_encoded))
print("After one merge")
print(merged_sample)

aaabbaababbaaabba
Before merging:
[97, 97, 97, 98, 98, 97, 97, 98, 97, 98, 98, 97, 97, 97, 98, 98, 97]
After one merge
[256, 97, 98, 98, 256, 98, 97, 98, 98, 256, 97, 98, 98, 97]

In [9]:
class BPETokenizer():
    def __init__(self):
        self.merges: dict[Pair, int] = {}
        # We want each token id to be converted into byte or bytes
        # The first 0-255 token ids already are directly their byte versions
        self.vocab: dict[int, bytes] = {token_id: bytes([token_id]) for token_id in range(256)}
    
    def train(
            self,
            training_text: str,
            vocab_size: int,
            min_pair_frequency: int = 2,
    ) -> None:
        
        encoded = list(training_text.encode("utf-8"))
        encoded = self._apply_merge_rules(encoded)
        
        applied_merges = len(self.merges)
        curr_vocab_size = applied_merges + 256
        
        while curr_vocab_size < vocab_size:
            freq_counter = pair_freq_counter(encoded)
            most_freq_pair = select_pair(freq_counter, min_pair_frequency)
            if most_freq_pair is None:
                break

            new_token_id = applied_merges + 256
            self.merges[most_freq_pair] = new_token_id
            self.vocab[new_token_id] = self.vocab[most_freq_pair[0]] + self.vocab[most_freq_pair[1]]
            encoded = apply_merge(encoded, most_freq_pair, new_token_id)
            applied_merges += 1
            curr_vocab_size += 1

    def encode(
            self,
            text: str,
    ) -> list[int]:
        ids = list(text.encode("utf-8"))
        return self._apply_merge_rules(ids)

    def decode(
            self,
            ids: list[int]
    ) -> str:
        
        byte_sequence = bytearray()
        for token_id in ids:
            byte_sequence.extend(self.vocab[token_id])
        
        return byte_sequence.decode("utf-8")


    def _apply_merge_rules(self, ids: list[int]) -> list[int]:
        for pair, new_id in self.merges.items():
            ids = apply_merge(ids, pair, new_id)
        return ids

In [10]:
sample_string = "aaabbaababbaaabbaşşIIİİaaİAİAİA"
sample_encoded = sample_string.encode("utf-8")

bpe_tokenizer = BPETokenizer()
bpe_tokenizer.train(sample_string, 300, 2)
print(sample_string)
print(bpe_tokenizer.merges)
print(bpe_tokenizer.encode(sample_string))
print(bpe_tokenizer.decode(sample_encoded))

aaabbaababbaaabbaşşIIİİaaİAİAİA
{(97, 97): 256, (196, 176): 257, (97, 98): 258, (258, 98): 259, (257, 65): 260, (256, 259): 261, (197, 159): 262, (260, 260): 263}
[261, 256, 98, 259, 261, 97, 262, 262, 73, 73, 257, 257, 256, 263, 260]
aaabbaababbaaabbaşşIIİİaaİAİAİA

In [11]:
new_tokenizer = BPETokenizer()

for i in range(500):
    new_tokenizer.train(train_set[i]["whole_func_string"], 1000, 2)

print(len(new_tokenizer.vocab))
sample_code = "def hello_world(name): print('hello', name)"
print(sample_code)
print(new_tokenizer.encode(sample_code))
print(new_tokenizer.decode(new_tokenizer.encode(sample_code)))
print(new_tokenizer.merges)

1000
def hello_world(name): print('hello', name)
[266, 345, 104, 327, 268, 565, 267, 108, 100, 40, 110, 97, 298, 41, 350, 465, 452, 40, 39, 104, 327, 268, 39, 292, 110, 97, 298, 41]
def hello_world(name): print('hello', name)
{(32, 32): 256, (256, 256): 257, (257, 257): 258, (115, 101): 259, (10, 258): 260, (259, 103): 261, (111, 110): 262, (116, 105): 263, (115, 116): 264, (100, 105): 265, (100, 101): 266, (111, 114): 267, (108, 111): 268, (61, 32): 269, (115, 99): 270, (263, 262): 271, (264, 97): 272, (32, 269): 273, (95, 265): 274, (41, 260): 275, (97, 271): 276, (259, 108): 277, (277, 102): 278, (267, 266): 279, (279, 114): 280, (103, 101): 281, (278, 46): 282, (35, 32): 283, (261, 95): 284, (284, 98): 285, (285, 280): 286, (109, 97): 287, (97, 114): 288, (105, 110): 289, (116, 276): 290, (121, 46): 291, (44, 32): 292, (260, 257): 293, (116, 101): 294, (268, 119): 295, (114, 101): 296, (287, 281): 297, (109, 101): 298, (270, 105): 299, (299, 112): 300, (108, 97): 301, (99, 101): 302, (272, 110): 303, (111, 117): 304, (109, 115): 305, (270, 262): 306, (306, 263): 307, (307, 110): 308, (308, 117): 309, (309, 105): 310, (310, 116): 311, (311, 121): 312, (110, 112): 313, (313, 46): 314, (300, 291): 315, (268, 103): 316, (46, 266): 317, (303, 302): 318, (288, 121): 319, (319, 274): 320, (295, 32): 321, (296, 115): 322, (109, 112): 323, (112, 101): 324, (272, 116): 325, (325, 115): 326, (101, 108): 327, (40, 261): 328, (275, 283): 329, (98, 117): 330, (330, 103): 331, (40, 286): 332, (98, 304): 333, (333, 110): 334, (334, 100): 335, (335, 320): 336, (336, 301): 337, (337, 290): 338, (338, 274): 339, (339, 318): 340, (260, 258): 341, (259, 100): 342, (342, 51): 343, (258, 258): 344, (102, 32): 345, (34, 34): 346, (105, 115): 347, (111, 108): 348, (32, 261): 349, (58, 32): 350, (91, 34): 351, (115, 34): 352, (93, 273): 353, (112, 288): 354, (354, 97): 355, (32, 50): 356, (315, 110): 357, (357, 265): 358, (358, 297): 359, (359, 46): 360, (316, 281): 361, (361, 114): 362, (362, 317): 363, (363, 331): 364, (364, 40): 365, (262, 101): 366, (104, 111): 367, (41, 32): 368, (112, 100): 369, (95, 305): 370, (370, 103): 371, (371, 99): 372, (372, 95): 373, (101, 112): 374, (274, 312): 375, (265, 312): 376, (376, 32): 377, (321, 322): 378, (378, 348): 379, (379, 117): 380, (380, 271): 381, (105, 297): 382, (298, 110): 383, (383, 290): 384, (116, 32): 385, (272, 114): 386, (386, 116): 387, (263, 298): 388, (282, 261): 389, (46, 97): 390, (390, 264): 391, (391, 121): 392, (392, 324): 393, (393, 40): 394, (275, 282): 395, (395, 326): 396, (396, 351): 397, (46, 115): 398, (260, 283): 399, (294, 114): 400, (355, 305): 401, (273, 360): 402, (99, 262): 403, (78, 366): 404, (41, 329): 405, (332, 41): 406, (341, 257): 407, (407, 40): 408, (408, 340): 409, (409, 32): 410, (410, 42): 411, (411, 356): 412, (412, 368): 413, (413, 43): 414, (414, 32): 415, (415, 49): 416, (416, 44): 417, (294, 323): 418, (58, 293): 419, (41, 292): 420, (275, 257): 421, (421, 369): 422, (122, 111): 423, (423, 111): 424, (424, 109): 425, (264, 374): 426, (268, 99): 427, (427, 97): 428, (428, 108): 429, (429, 105): 430, (430, 122): 431, (431, 276): 432, (260, 346): 433, (433, 34): 434, (434, 260): 435, (377, 289): 436, (436, 32): 437, (98, 97): 438, (347, 32): 439, (32, 382): 440, (349, 384): 441, (296, 116): 442, (442, 117): 443, (443, 114): 444, (444, 110): 445, (105, 323): 446, (446, 267): 447, (447, 385): 448, (10, 260): 449, (260, 261): 450, (45, 32): 451, (289, 116): 452, (452, 56): 453, (397, 321): 454, (454, 108): 455, (455, 101): 456, (456, 118): 457, (457, 327): 458, (118, 111): 459, (459, 120): 460, (460, 327): 461, (461, 352): 462, (462, 353): 463, (463, 314): 464, (112, 114): 465, (465, 111): 466, (101, 100): 467, (400, 115): 468, (389, 401): 469, (365, 34): 470, (470, 286): 471, (471, 350): 472, (472, 37): 473, (473, 352): 474, (474, 292): 475, (475, 315): 476, (476, 326): 477, (477, 317): 478, (478, 270): 479, (479, 114): 480, (480, 105): 481, (481, 98): 482, (482, 101): 483, (483, 332): 484, (484, 292): 485, (485, 97): 486, (486, 120): 487, (487, 347): 488, (488, 61): 489, (489, 404): 490, (490, 405): 491, (365, 264): 492, (492, 114): 493, (493, 40): 494, (494, 314): 495, (109, 267): 496, (496, 112): 497, (497, 367): 498, (498, 316): 499, (499, 291): 500, (44, 293): 501, (417, 417): 502, (44, 260): 503, (105, 345): 504, (504, 282): 505, (115, 419): 506, (282, 418): 507, (507, 373): 508, (508, 295): 509, (509, 322): 510, (510, 375): 511, (511, 273): 512, (273, 343): 513, (513, 46): 514, (514, 343): 515, (256, 283): 516, (516, 420): 517, (517, 403): 518, (518, 116): 519, (519, 304): 520, (520, 114): 521, (521, 61): 522, (522, 261): 523, (523, 422): 524, (524, 398): 525, (525, 367): 526, (526, 119): 527, (527, 40): 528, (394, 39): 529, (344, 344): 530, (114, 97): 531, (531, 112): 532, (532, 104): 533, (103, 533): 534, (97, 108): 535, (117, 110): 536, (282, 95): 537, (534, 46): 538, (101, 115): 539, (535, 116): 540, (536, 288): 541, (541, 105): 542, (542, 539): 543, (543, 540): 544, (104, 97): 545, (545, 324): 546, (104, 105): 547, (103, 104): 548, (40, 368): 549, (289, 100): 550, (268, 50): 551, (551, 547): 552, (105, 116): 553, (34, 353): 554, (554, 40): 555, (555, 388): 556, (556, 46): 557, (557, 388): 558, (558, 549): 559, (559, 451): 560, (560, 537): 561, (561, 387): 562, (562, 95): 563, (563, 388): 564, (95, 119): 565, (565, 101): 566, (566, 105): 567, (567, 548): 568, (568, 116): 569, (108, 289): 570, (570, 107): 571, (571, 115): 572, (322, 546): 573, (573, 40): 574, (109, 117): 575, (575, 108): 576, (403, 264): 577, (105, 122): 578, (578, 101): 579, (373, 426): 580, (40, 41): 581, (100, 95): 582, (101, 97): 583, (421, 283): 584, (95, 103): 585, (95, 552): 586, (102, 289): 587, (116, 97): 588, (273, 537): 589, (282, 326): 590, (564, 275): 591, (461, 115): 592, (288, 583): 593, (593, 569): 594, (305, 550): 595, (595, 115): 596, (46, 574): 597, (292, 49): 598, (467, 515): 599, (467, 398): 600, (600, 367): 601, (601, 119): 602, (32, 102): 603, (114, 117): 604, (467, 281): 605, (95, 289): 606, (104, 288): 607, (607, 582): 608, (608, 577): 609, (609, 531): 610, (610, 452): 611, (611, 115): 612, (449, 590): 613, (351, 116): 614, (294, 95): 615, (40, 538): 616, (576, 95): 617, (544, 50): 618, (544, 91): 619, (292, 48): 620, (93, 597): 621, (110, 572): 622, (448, 343): 623, (602, 40): 624, (585, 99): 625, (114, 536): 626, (112, 121): 627, (117, 116): 628, (324, 114): 629, (629, 102): 630, (630, 267): 631, (100, 32): 632, (100, 97): 633, (633, 588): 634, (114, 105): 635, (605, 115): 636, (261, 384): 637, (114, 111): 638, (638, 109): 639, (107, 40): 640, (95, 322): 641, (589, 580): 642, (61, 61): 643, (613, 614): 644, (51, 46): 645, (592, 579): 646, (112, 108): 647, (647, 553): 648, (397, 116): 649, (282, 105): 650, (650, 109): 651, (651, 103): 652, (273, 314): 653, (45, 49): 654, (654, 598): 655, (624, 584): 656, (292, 618): 657, (95, 587): 658, (658, 347): 659, (659, 104): 660, (576, 263): 661, (661, 270): 662, (662, 535): 663, (663, 101): 664, (626, 40): 665, (41, 58): 666, (32, 71): 667, (32, 119): 668, (668, 553): 669, (669, 104): 670, (587, 101): 671, (111, 345): 672, (381, 32): 673, (603, 105): 674, (674, 114): 675, (675, 264): 676, (426, 32): 677, (262, 32): 678, (577, 604): 679, (679, 99): 680, (110, 111): 681, (117, 259): 682, (102, 639): 683, (81, 116): 684, (627, 113): 685, (685, 116): 686, (686, 82): 687, (687, 101): 688, (688, 109): 689, (689, 111): 690, (690, 118): 691, (691, 101): 692, (692, 73): 693, (693, 313): 694, (694, 628): 695, (695, 72): 696, (696, 111): 697, (697, 111): 698, (395, 373): 699, (699, 552): 700, (700, 641): 701, (701, 579): 702, (606, 553): 703, (395, 95): 704, (704, 580): 705, (95, 295): 706, (348, 117): 707, (707, 271): 708, (95, 637): 709, (40, 329): 710, (581, 644): 711, (711, 645): 712, (591, 534): 713, (40, 293): 714, (61, 282): 715, (646, 501): 716, (95, 588): 717, (717, 98): 718, (718, 108): 719, (719, 101): 720, (606, 266): 721, (721, 120): 722, (722, 61): 723, (723, 84): 724, (724, 604): 725, (725, 101): 726, (10, 399): 727, (538, 281): 728, (728, 110): 729, (729, 101): 730, (730, 531): 731, (731, 615): 732, (732, 438): 733, (733, 259): 734, (734, 585): 735, (735, 635): 736, (736, 100): 737, (398, 648): 738, (738, 95): 739, (739, 592): 740, (564, 41): 741, (617, 287): 742, (742, 115): 743, (743, 107): 744, (617, 118): 745, (745, 535): 746, (116, 572): 747, (95, 99): 748, (61, 404): 749, (616, 596): 750, (586, 653): 751, (751, 104): 752, (752, 272): 753, (753, 99): 754, (754, 640): 755, (619, 550): 756, (756, 620): 757, (620, 621): 758, (598, 621): 759, (655, 41): 760, (760, 93): 761, (538, 636): 762, (623, 10): 763, (763, 293): 764, (764, 599): 765, (765, 40): 766, (766, 619): 767, (767, 58): 768, (768, 292): 769, (769, 58): 770, (652, 398): 771, (771, 546): 772, (772, 41): 773, (773, 421): 774, (584, 656): 775, (775, 623): 776, (776, 293): 777, (777, 283): 778, (778, 599): 779, (622, 657): 780, (780, 292): 781, (781, 596): 782, (57, 660): 783, (783, 95): 784, (784, 631): 785, (785, 109): 786, (786, 625): 787, (787, 95): 788, (788, 97): 789, (789, 110): 790, (790, 582): 791, (791, 574): 792, (95, 547): 793, (793, 50): 794, (794, 268): 795, (795, 95): 796, (32, 672): 797, (547, 548): 798, (798, 32): 799, (799, 322): 800, (800, 708): 801, (801, 32): 802, (698, 107): 803, (40, 275): 804, (118, 535): 805, (805, 117): 806, (806, 539): 807, (550, 115): 808, (570, 101): 809, (809, 288): 810, (810, 95): 811, (101, 32): 812, (301, 98): 813, (108, 32): 814, (91, 105): 815, (815, 93): 816, (32, 289): 817, (91, 48): 818, (116, 104): 819, (811, 808): 820, (266, 120): 821, (287, 120): 822, (807, 91): 823, (817, 821): 824, (267, 32): 825, (32, 49): 826, (93, 44): 827, (827, 341): 828, (32, 52): 829, (105, 287): 830, (830, 814): 831, (813, 327): 832, (108, 101): 833, (811, 634): 834, (823, 820): 835, (835, 816): 836, (98, 121): 837, (32, 807): 838, (824, 539): 839, (273, 91): 840, (93, 449): 841, (634, 32): 842, (822, 831): 843, (806, 101): 844, (536, 105): 845, (845, 113): 846, (846, 117): 847, (819, 101): 848, (40, 808): 849, (93, 32): 850, (834, 816): 851, (838, 32): 852, (115, 105): 853, (837, 839): 854, (32, 99): 855, (840, 818): 856, (856, 826): 857, (828, 818): 858, (858, 356): 859, (859, 356): 860, (93, 841): 861, (828, 91): 862, (829, 829): 863, (819, 812): 864, (288, 812): 865, (292, 105): 866, (866, 385): 867, (867, 119): 868, (868, 105): 869, (869, 108): 870, (870, 814): 871, (871, 588): 872, (872, 107): 873, (843, 844): 874, (97, 110): 875, (399, 813): 876, (108, 808): 877, (653, 847): 878, (878, 101): 879, (879, 849): 880, (399, 807): 881, (273, 634): 882, (446, 833): 883, (883, 384): 884, (101, 296): 885, (833, 110): 886, (886, 40): 887, (102, 825): 888, (817, 32): 889, (314, 822): 890, (653, 97): 891, (891, 115): 892, (892, 288): 893, (893, 531): 894, (894, 121): 895, (895, 40): 896, (896, 807): 897, (897, 41): 898, (114, 32): 899, (46, 531): 900, (900, 118): 901, (901, 327): 902, (902, 804): 903, (110, 281): 904, (504, 836): 905, (905, 850): 906, (58, 341): 907, (907, 283): 908, (341, 836): 909, (909, 353): 910, (910, 851): 911, (267, 105): 912, (912, 103): 913, (95, 913): 914, (95, 115): 915, (115, 107): 916, (287, 916): 917, (287, 108): 918, (918, 108): 919, (915, 919): 920, (915, 546): 921, (917, 914): 922, (920, 606): 923, (923, 914): 924, (913, 921): 925, (808, 914): 926, (808, 924): 927, (32, 439): 928, (91, 922): 929, (292, 925): 930, (115, 32): 931, (322, 708): 932, (400, 32): 933, (95, 116): 934, (32, 43): 935, (890, 849): 936, (368, 43): 937, (465, 289): 938, (938, 385): 939, (32, 97): 940, (84, 604): 941, (941, 101): 942, (808, 273): 943, (296, 832): 944, (917, 930): 945, (288, 531): 946, (104, 885): 947, (947, 928): 948, (289, 535): 949, (949, 32): 950, (932, 32): 951, (951, 40): 952, (110, 117): 953, (98, 101): 954, (828, 256): 955, (955, 91): 956, (273, 425): 957, (957, 934): 958, (958, 111): 959, (959, 921): 960, (292, 100): 961, (961, 116): 962, (962, 121): 963, (963, 324): 964, (964, 61): 965, (965, 314): 966, (966, 453): 967, (653, 288): 968, (968, 875): 969, (969, 281): 970, (970, 40): 971, (917, 398): 972, (41, 597): 973, (925, 41): 974, (936, 924): 975, (975, 937): 976, (976, 826): 977, (399, 939): 978, (289, 821): 979, (399, 448): 980, (369, 98): 981, (927, 929): 982, (32, 61): 983, (983, 269): 984, (984, 942): 985, (926, 929): 986, (314, 109): 987, (987, 289): 988, (988, 849): 989, (940, 102): 990, (990, 933): 991, (991, 944): 992, (992, 289): 993, (993, 103): 994, (994, 350): 995, (935, 32): 996, (353, 48): 997, (997, 399): 998, (95, 805): 999}

In [12]:
corpus = "\n\n".join(train_set[:500]["whole_func_string"])

In [13]:
print(len(corpus))
print(len(corpus.encode("utf-8")))
print(corpus[:100])
print(corpus[-50:])

411271
411298
def __msgc_step3_discontinuity_localization(self):
        """
        Estimate discontinuity in bas
t.read_port_stats()
        return self.statistics

In [14]:
test_tokenizer = BPETokenizer()
test_tokenizer.train(corpus, 10000, 2)

In [15]:
print(len(test_tokenizer.vocab))
sample_code = "def hello_world(name): print('hello', name)"
print(sample_code)
print(test_tokenizer.encode(sample_code))
print(test_tokenizer.decode(test_tokenizer.encode(sample_code)))

10000
def hello_world(name): print('hello', name)
[336, 104, 330, 291, 95, 1008, 487, 1291, 6695, 4781, 104, 330, 291, 687, 339, 41]
def hello_world(name): print('hello', name)